apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-express-deployment
  labels:
    app: node-express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-express
  template:
    metadata:
      labels:
        app: node-express
    spec:
      containers:
      - name: node-express-container
        image: developerzaid/kubernetes-dynatrace-node-app:latest

        ports:
        - containerPort: 3000
