apiVersion: v1
kind: Service
metadata:
  name: node-express-service
spec:
  selector:
    app: node-express
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007
  type: NodePort
